### ISSUE TITLE
why two CI actions ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-JAVA#56]
two YAML files in github actions
`testAndBuild.yml`
```
on:
  push:
    branches: 
      - v*
```

`testPR.yml` :
```
on:
  pull_request:
    branches: 
      - v*
```
do we need both ?
